Migrate framework dependencies for GitHub ITs
wazuh/qa-integration-framework pull request #11
Opened 2023-06-22 08:55 UTC by mjcr99

|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/17427|

## Description
This PR includes all the necessary changes to give support to the migrated tests in the wazuh/wazuh repository. These tests will use this new structure. This PR removes all the unnecessary utilities, functions, classes, etc. that were not being used by the old ITs and adds some modifications.

2023-06-22 12:12 UTC, Deblintrake09 submitted a review, later dismissed
LGTM!

2023-06-22 17:03 UTC, TomasTurina requested changes

2023-06-22 17:03 UTC, TomasTurina commented on src/wazuh_testing/modules/integrations/event_monitors.py
I think these functions should be test fixtures. Check for example: https://github.com/wazuh/wazuh/blob/4157_tests_migration/tests/integration/test_analysisd/conftest.py#L67

2023-06-22 17:03 UTC, TomasTurina commented on src/wazuh_testing/modules/integrations/event_monitors.py
> +    callback = f".*ERROR: {error_type} content for tag '{tag}' at module '{integration}'."
This should be a pattern in `patterns.py`. Check this example: https://github.com/wazuh/qa-integration-framework/blob/4157_tests_migration/src/wazuh_testing/modules/analysisd/patterns.py

2023-06-22 17:03 UTC, TomasTurina commented on src/wazuh_testing/modules/integrations/event_monitors.py
> +    callback = f".*INFO: Module {integration} started."
This should be a pattern in `patterns.py`. Check this example: https://github.com/wazuh/qa-integration-framework/blob/4157_tests_migration/src/wazuh_testing/modules/analysisd/patterns.py

2023-06-22 17:03 UTC, TomasTurina commented on src/wazuh_testing/utils/callbacks.py
> +    return new_callback
Don't remove new line at the end of the file.

2023-06-26 09:34 UTC, mjcr99 commented on src/wazuh_testing/utils/callbacks.py
> +    return new_callback
Fixed with this [commit](https://github.com/wazuh/qa-integration-framework/pull/11/commits/3a231555b1fac22e50dd5f30aa8c137d27b4e39a)

2023-06-26 09:34 UTC, mjcr99 commented on src/wazuh_testing/modules/integrations/event_monitors.py
> +    callback = f".*INFO: Module {integration} started."
Fixed with this [commit](https://github.com/wazuh/qa-integration-framework/pull/11/commits/3a231555b1fac22e50dd5f30aa8c137d27b4e39a)

2023-06-26 09:34 UTC, mjcr99 commented on src/wazuh_testing/modules/integrations/event_monitors.py
> +    callback = f".*ERROR: {error_type} content for tag '{tag}' at module '{integration}'."
Fixed with this [commit](https://github.com/wazuh/qa-integration-framework/pull/11/commits/3a231555b1fac22e50dd5f30aa8c137d27b4e39a)

2023-06-26 09:34 UTC, mjcr99 commented on src/wazuh_testing/modules/integrations/__init__.py
> +LOCAL_INTERNAL_OPTIONS = {'wazuh_modules.debug': 2 }
Fixed with this [commit](https://github.com/wazuh/qa-integration-framework/pull/11/commits/3a231555b1fac22e50dd5f30aa8c137d27b4e39a)

2023-06-26 12:55 UTC, mjcr99 commented on src/wazuh_testing/modules/integrations/__init__.py
Fixed with this [commit](https://github.com/wazuh/qa-integration-framework/pull/11/commits/3a231555b1fac22e50dd5f30aa8c137d27b4e39a)

2023-06-26 12:57 UTC, mjcr99 commented on src/wazuh_testing/modules/integrations/event_monitors.py
Fixed in framework with this [commit](https://github.com/wazuh/qa-integration-framework/pull/11/commits/3ef72dd243eb843515f9c6075d2899bab714a4ce)
Fixed in wazuh/wazuh with this [commit](https://github.com/wazuh/wazuh/pull/17621/commits/d838224bd5ffa7fad4853f1a299264bb9371c533)

2023-06-29 13:34 UTC, TomasTurina commented on src/wazuh_testing/constants/paths/configurations.py
> +CUSTOM_RULES_FILE = os.path.join(CUSTOM_RULES_PATH, 'local_rules.xml')
Don't modify this

2023-06-29 13:34 UTC, TomasTurina commented on src/wazuh_testing/constants/paths/logs.py
> +ARCHIVES_JSON_PATH = os.path.join(BASE_LOGS_PATH, 'archives', 'archives.json')
Don't modify this

2023-06-29 13:34 UTC, TomasTurina commented on src/wazuh_testing/tools/mocking.py
I think this file shouldn't exist here.

2023-06-29 13:34 UTC, TomasTurina commented on src/wazuh_testing/modules/modulesd/configuration.py
> +LOCAL_INTERNAL_OPTIONS = 'wazuh_modules.debug'
Maybe a more specific name?
```suggestion
MODULESD_DEBUG = 'wazuh_modules.debug'
```

2023-06-29 13:34 UTC, TomasTurina commented on src/wazuh_testing/modules/modulesd/patterns.py
> +MODULESD_STARTED = r".*INFO: Module {integration} started."
Add new line at the end of the file.

2023-06-29 16:49 UTC, mjcr99 commented on src/wazuh_testing/modules/modulesd/patterns.py
> +MODULESD_STARTED = r".*INFO: Module {integration} started."
Fixed with https://github.com/wazuh/qa-integration-framework/pull/11/commits/cab526fee44da8631084c580c3c5ca79a91ea38a

2023-06-29 16:49 UTC, mjcr99 commented on src/wazuh_testing/modules/modulesd/configuration.py
> +LOCAL_INTERNAL_OPTIONS = 'wazuh_modules.debug'
Fixed with https://github.com/wazuh/qa-integration-framework/pull/11/commits/cab526fee44da8631084c580c3c5ca79a91ea38a

2023-06-29 16:49 UTC, mjcr99 commented on src/wazuh_testing/tools/mocking.py
It's present because the branch was removed and rebuilt from `4157_tests_migration` cherry-picking the previous changes

2023-06-29 16:49 UTC, mjcr99 commented on src/wazuh_testing/constants/paths/logs.py
> +ARCHIVES_JSON_PATH = os.path.join(BASE_LOGS_PATH, 'archives', 'archives.json')
Fixed with https://github.com/wazuh/qa-integration-framework/pull/11/commits/cab526fee44da8631084c580c3c5ca79a91ea38a

2023-06-29 16:49 UTC, mjcr99 commented on src/wazuh_testing/constants/paths/configurations.py
> +CUSTOM_RULES_FILE = os.path.join(CUSTOM_RULES_PATH, 'local_rules.xml')
Fixed with https://github.com/wazuh/qa-integration-framework/pull/11/commits/cab526fee44da8631084c580c3c5ca79a91ea38a

2023-07-04 15:52 UTC, TomasTurina requested changes

2023-07-04 15:52 UTC, TomasTurina commented on src/wazuh_testing/tools/mocking.py
This file shouldn't exist. Remove it.

2023-07-05 10:39 UTC, mjcr99 commented on src/wazuh_testing/tools/mocking.py
Fixed with https://github.com/wazuh/qa-integration-framework/pull/11/commits/4b8524f9811156a88a72da79d400add24be8d1c3

2023-07-05 10:43 UTC, mjcr99 commented on src/wazuh_testing/tools/mocking.py
Fixed with https://github.com/wazuh/qa-integration-framework/pull/11/commits/d1989a0f1df94079b09651aa76446d997da899bc

2023-07-07 19:15 UTC, TomasTurina approved these changes

2023-07-17 14:51 UTC, TomasTurina submitted a review, later dismissed

2023-07-21 14:16 UTC, TomasTurina submitted a review, later dismissed

2023-07-21 14:23 UTC, TomasTurina approved these changes

2023-07-21 14:24 UTC, merged