Add Vulnerability Detector framework
wazuh/qa-integration-framework pull request #14
Opened 2023-07-03 20:17 UTC by Deblintrake09

| Related issues
|--
| closes #9

## Description

This PR aims to migrate the dependencies of the VDT tests from the old framework (wazuh/wazuh-qa repo) to this brand-new repository, and also apply a refactor to remove unused code or duplicated code.

2023-07-07 19:44 UTC, TomasTurina requested changes
You need to rebase.

2023-07-07 19:44 UTC, TomasTurina commented on src/wazuh_testing/modules/vulnerability_detector/__init__.py
> +LOCAL_INTERNAL_OPTIONS = {'wazuh_modules.debug': '2', 'monitord.rotate_log': '0'}
Put this in a `configuration.py` file and set the value of the option in the tests. Check for example: https://github.com/wazuh/qa-integration-framework/blob/main/src/wazuh_testing/modules/analysisd/configuration.py

2023-07-07 19:44 UTC, TomasTurina commented on src/wazuh_testing/modules/vulnerability_detector/__init__.py
> +CPE_HELPER_PATH = os.path.join(WAZUH_PATH, 'queue', 'vulnerabilities', 'dictionaries', 'cpe_helper.json')
I think this should be in `constants/paths`, maybe in `databases.py` (it is a DB in JSON format).

2023-07-07 19:44 UTC, TomasTurina commented on src/wazuh_testing/modules/vulnerability_detector/__init__.py
> +from wazuh_testing.constants.paths import WAZUH_PATH
Remember to remove this line after applying previous comment.

2023-07-07 19:44 UTC, TomasTurina commented on src/wazuh_testing/modules/vulnerability_detector/event_monitors.py
I think these functions should be in the tests. Check for example: https://github.com/wazuh/wazuh/blob/master/tests/integration/test_analysisd/conftest.py#L67 or https://github.com/wazuh/wazuh/blob/master/tests/integration/test_analysisd/test_signature_id/test_invalid_signature_id.py#L124

2023-07-07 19:44 UTC, TomasTurina commented on src/wazuh_testing/modules/vulnerability_detector/packages.py
Rename this file to `utils.py`. Check for example: https://github.com/wazuh/qa-integration-framework/blob/main/src/wazuh_testing/modules/analysisd/utils.py

2023-07-07 19:44 UTC, TomasTurina commented on src/wazuh_testing/modules/vulnerability_detector/patterns.py
> +from wazuh_testing.modules.vulnerability_detector import VULNERABILITY_DETECTOR_PREFIX
```suggestion
from . import VULNERABILITY_DETECTOR_PREFIX
```

2023-07-07 19:44 UTC, TomasTurina commented on src/wazuh_testing/modules/vulnerability_detector/patterns.py
> +
Remove extra empty line.

2023-07-07 19:44 UTC, TomasTurina commented on src/wazuh_testing/modules/vulnerability_detector/patterns.py
> +
Remove extra empty line.

2023-07-07 19:44 UTC, TomasTurina commented on src/wazuh_testing/modules/vulnerability_detector/patterns.py
> +
Remove extra empty line.

2023-07-07 19:44 UTC, TomasTurina commented on src/wazuh_testing/utils/database.py
> +    services.control_service('stop', daemon='wazuh-db')
Use constant: https://github.com/wazuh/qa-integration-framework/blob/main/src/wazuh_testing/constants/daemons.py#L19

2023-07-07 19:44 UTC, TomasTurina commented on src/wazuh_testing/utils/database.py
> +        services.control_service('start', daemon='wazuh-db')
Use constant: https://github.com/wazuh/qa-integration-framework/blob/main/src/wazuh_testing/constants/daemons.py#L19

2023-07-07 19:44 UTC, TomasTurina commented on src/wazuh_testing/utils/database.py
> +    services.control_service('stop', daemon='wazuh-db')
Use constant: https://github.com/wazuh/qa-integration-framework/blob/main/src/wazuh_testing/constants/daemons.py#L19

2023-07-07 19:44 UTC, TomasTurina commented on src/wazuh_testing/utils/database.py
> +        services.control_service('start', daemon='wazuh-db')
Use constant: https://github.com/wazuh/qa-integration-framework/blob/main/src/wazuh_testing/constants/daemons.py#L19

2023-07-07 19:44 UTC, TomasTurina commented on src/wazuh_testing/utils/database.py
> +def execute_sqlite_query(cursor, query: str) -> None:
Make function private.

2023-07-07 19:44 UTC, TomasTurina commented on src/wazuh_testing/utils/file.py
> +    if sys.platform != 'win32':
Use constant: https://github.com/wazuh/qa-integration-framework/blob/main/src/wazuh_testing/constants/platforms.py#L8

2023-07-25 13:31 UTC, Deblintrake09 commented on src/wazuh_testing/utils/file.py
> +    if sys.platform != 'win32':
Fixed in https://github.com/wazuh/qa-integration-framework/pull/14/commits/34b7b4e29f886a09dcf24220bdfea509bb0b7850

2023-07-25 13:31 UTC, Deblintrake09 commented on src/wazuh_testing/utils/database.py
> +        services.control_service('start', daemon='wazuh-db')
Fixed in https://github.com/wazuh/qa-integration-framework/pull/14/commits/34b7b4e29f886a09dcf24220bdfea509bb0b7850

2023-07-25 13:31 UTC, Deblintrake09 commented on src/wazuh_testing/utils/database.py
> +    services.control_service('stop', daemon='wazuh-db')
Fixed in https://github.com/wazuh/qa-integration-framework/pull/14/commits/34b7b4e29f886a09dcf24220bdfea509bb0b7850

2023-07-25 13:31 UTC, Deblintrake09 commented on src/wazuh_testing/utils/database.py
> +        services.control_service('start', daemon='wazuh-db')
Fixed in https://github.com/wazuh/qa-integration-framework/pull/14/commits/34b7b4e29f886a09dcf24220bdfea509bb0b7850

2023-07-25 13:31 UTC, Deblintrake09 commented on src/wazuh_testing/utils/database.py
> +    services.control_service('stop', daemon='wazuh-db')
Fixed in https://github.com/wazuh/qa-integration-framework/pull/14/commits/34b7b4e29f886a09dcf24220bdfea509bb0b7850

2023-07-25 19:11 UTC, Deblintrake09 commented on src/wazuh_testing/utils/database.py
> +def execute_sqlite_query(cursor, query: str) -> None:
As discussed this change is unnecesary and will not be applied.

2023-07-25 19:12 UTC, Deblintrake09 commented on src/wazuh_testing/modules/vulnerability_detector/patterns.py
> +
Done in https://github.com/wazuh/qa-integration-framework/pull/14/commits/dfe95af3de3d5eaaaada9a5bb93eccad430ed1d8

2023-07-25 19:12 UTC, Deblintrake09 commented on src/wazuh_testing/modules/vulnerability_detector/patterns.py
> +
Done in https://github.com/wazuh/qa-integration-framework/pull/14/commits/dfe95af3de3d5eaaaada9a5bb93eccad430ed1d8

2023-07-25 19:12 UTC, Deblintrake09 commented on src/wazuh_testing/modules/vulnerability_detector/patterns.py
> +
Done in https://github.com/wazuh/qa-integration-framework/pull/14/commits/dfe95af3de3d5eaaaada9a5bb93eccad430ed1d8

2023-07-25 19:12 UTC, Deblintrake09 commented on src/wazuh_testing/modules/vulnerability_detector/patterns.py
> +from wazuh_testing.modules.vulnerability_detector import VULNERABILITY_DETECTOR_PREFIX
Done in https://github.com/wazuh/qa-integration-framework/pull/14/commits/dfe95af3de3d5eaaaada9a5bb93eccad430ed1d8

2023-07-25 19:13 UTC, Deblintrake09 commented on src/wazuh_testing/modules/vulnerability_detector/__init__.py
> +CPE_HELPER_PATH = os.path.join(WAZUH_PATH, 'queue', 'vulnerabilities', 'dictionaries', 'cpe_helper.json')
Done in https://github.com/wazuh/qa-integration-framework/pull/14/commits/adb5006aedeb76968a6e2cc208a60677ec73706e

2023-07-25 19:26 UTC, Deblintrake09 commented on src/wazuh_testing/modules/vulnerability_detector/__init__.py
> +LOCAL_INTERNAL_OPTIONS = {'wazuh_modules.debug': '2', 'monitord.rotate_log': '0'}
Done in https://github.com/wazuh/qa-integration-framework/pull/14/commits/adb5006aedeb76968a6e2cc208a60677ec73706e.

Moved to configuration.py and renamed the LOCAL_INTERNAL_OPTIONS variable to DEFAULT_LOCAL_INTERNAL_OPTIONS. There is no need to redefine the values in every test if it will be the same in all cases (All VDT tests up to this point use the same configuration), the names of the options were extracted so they can be used to change values if needed.

2023-08-10 14:07 UTC, TomasTurina commented on src/wazuh_testing/__init__.py
> +FEEDS_PATH = Path(DATA_PATH, 'feeds')
Are you using this? If not, remove it.

2023-08-10 14:11 UTC, TomasTurina commented on src/wazuh_testing/constants/paths/databases.py
> +CPE_HELPER_PATH = os.path.join(WAZUH_PATH, 'queue', 'vulnerabilities', 'dictionaries', 'cpe_helper.json')
Add new line at the end.

2023-08-10 14:17 UTC, TomasTurina commented on src/wazuh_testing/modules/patterns.py
> +CONFIGURATION_ERROR = r'.*ERROR.*Configuration error at.*'
Put this pattern inside `src/wazuh_testing/modules/modulesd/patterns.py` since it is only used there.

2023-08-10 14:19 UTC, TomasTurina commented on src/wazuh_testing/modules/vulnerability_detector/__init__.py
> +import os
Remove unused import.

2023-08-10 14:21 UTC, TomasTurina commented on src/wazuh_testing/modules/vulnerability_detector/configuration.py
> +DEFAULT_LOCAL_INTERNAL_OPTIONS = {WAZUH_MODULES_DEBUG: '2', MONITORD_ROTATE_LOG: '0'}
We are defining this inside the tests.

2023-08-10 14:22 UTC, TomasTurina commented on src/wazuh_testing/modules/vulnerability_detector/configuration.py
This file is not necessary, remove it. Both definitions `wazuh_modules.debug` and `monitord.rotate_log` are already located in other files.

2023-08-10 14:25 UTC, TomasTurina commented on src/wazuh_testing/modules/vulnerability_detector/event_monitors.py
We rediscussed this with @QU3B1M and @mauromalara. We are placing these calls directly inside the tests to simplify the framework. Please, move this to the tests.

2023-08-10 14:36 UTC, TomasTurina commented on src/wazuh_testing/utils/database.py
> +import sqlite3
Use `DatabaseAdministrator` as wrapper of `sqlite3`.

(https://github.com/wazuh/qa-integration-framework/pull/22#discussion_r1277994805)

2023-08-10 14:40 UTC, TomasTurina commented on src/wazuh_testing/utils/file.py
> +def read_json_file(file_path: str) -> str:
Duplicated function.

2023-08-10 20:10 UTC, Deblintrake09 commented on src/wazuh_testing/__init__.py
> +FEEDS_PATH = Path(DATA_PATH, 'feeds')
This is being used in the VDT tests to get the Feed files.

2023-08-10 23:55 UTC, Deblintrake09 commented on src/wazuh_testing/utils/file.py
> +def read_json_file(file_path: str) -> str:
Removed in https://github.com/wazuh/qa-integration-framework/pull/14/commits/6a1551ab3062ce8a243771799ccb0676c03c7969

2023-08-10 23:56 UTC, Deblintrake09 commented on src/wazuh_testing/utils/database.py
> +import sqlite3
Fixed in https://github.com/wazuh/qa-integration-framework/pull/14/commits/62c2708ed99d1926ee5bda656b3d5325a368770f

2023-08-10 23:58 UTC, Deblintrake09 commented on src/wazuh_testing/tools/mitm.py
> +    def process_request(self, request ,
This was accidental. reverted.

2023-08-10 23:59 UTC, Deblintrake09 commented on src/wazuh_testing/modules/vulnerability_detector/event_monitors.py
Fixed in https://github.com/wazuh/qa-integration-framework/pull/14/commits/d3388a3ec9fb72b68bc4500c68bc248339807012

2023-08-10 23:59 UTC, Deblintrake09 commented on src/wazuh_testing/modules/vulnerability_detector/configuration.py
Fixed in https://github.com/wazuh/qa-integration-framework/pull/14/commits/d3388a3ec9fb72b68bc4500c68bc248339807012

2023-08-10 23:59 UTC, Deblintrake09 commented on src/wazuh_testing/modules/vulnerability_detector/configuration.py
> +DEFAULT_LOCAL_INTERNAL_OPTIONS = {WAZUH_MODULES_DEBUG: '2', MONITORD_ROTATE_LOG: '0'}
Fixed in https://github.com/wazuh/qa-integration-framework/pull/14/commits/d3388a3ec9fb72b68bc4500c68bc248339807012

2023-08-10 23:59 UTC, Deblintrake09 commented on src/wazuh_testing/modules/vulnerability_detector/__init__.py
> +import os
Fixed in https://github.com/wazuh/qa-integration-framework/pull/14/commits/7f15206f7dfd8065364803abd7f781283d9634ee

2023-08-11 00:00 UTC, Deblintrake09 commented on src/wazuh_testing/constants/paths/databases.py
> +CPE_HELPER_PATH = os.path.join(WAZUH_PATH, 'queue', 'vulnerabilities', 'dictionaries', 'cpe_helper.json')
Fixed in https://github.com/wazuh/qa-integration-framework/pull/14/commits/ebf4b8f5eda5cb3495145e9e3a2a2ea538ccec44

2023-08-11 00:00 UTC, Deblintrake09 commented on src/wazuh_testing/modules/patterns.py
> +CONFIGURATION_ERROR = r'.*ERROR.*Configuration error at.*'
Fixed in https://github.com/wazuh/qa-integration-framework/commit/7f15206f7dfd8065364803abd7f781283d9634ee

2023-08-23 15:14 UTC, TomasTurina submitted a review, later dismissed

2023-09-05 13:37 UTC, TomasTurina requested changes

2023-09-05 13:37 UTC, TomasTurina commented on src/wazuh_testing/modules/vulnerability_detector/configuration.py
These options doesn't belong here. Remove this file.
They are already located in `src/wazuh_testing/modules/monitord/configuration.py` and `src/wazuh_testing/modules/modulesd/configuration.py`

2023-09-12 22:27 UTC, Deblintrake09 commented on src/wazuh_testing/modules/vulnerability_detector/configuration.py
Done  in https://github.com/wazuh/qa-integration-framework/pull/14/commits/bcb7ab2285b4ddb90b81b5012f7f813c7bad424d

2023-10-25 17:18 UTC, TomasTurina approved these changes

2023-12-07 19:58 UTC, TomasTurina submitted a review, later dismissed

2023-12-11 19:01 UTC, TomasTurina approved these changes

2023-12-11 21:44 UTC, TomasTurina submitted a review, later dismissed

2023-12-11 22:58 UTC, TomasTurina approved these changes

2023-12-12 21:33 UTC, TomasTurina approved these changes

2023-12-12 22:41 UTC, merged