Allow setting different regions to generated AWS resources
wazuh/qa-integration-framework pull request #156
Opened 2024-05-07 11:30 UTC by fdalmaup

# Description

Closes #150. 
- Modifies S3 data generation methods and functions to generate resources for any specified region.
- Removes the `boto3` client instantiations from the framework, making it the responsibility of the executed tests to instantiate and pass them accordingly.
- Fixes related AWS database functions that were not correctly used after the rebase of the epic branch.

## Tests

<details><summary>Current working tests execution</summary>

```console
root@vagrant:/# pytest -x /wazuh/tests/integration/test_aws/test_log_groups.py 
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.4.0
rootdir: /wazuh/tests/integration, configfile: pytest.ini
plugins: metadata-3.1.1, html-3.1.1
collected 2 items                                                                                                                                                                                         

wazuh/tests/integration/test_aws/test_log_groups.py ..                                                                                                                                              [100%]

=========================================================================================== 2 passed in 46.91s ============================================================================================
root@vagrant:/# pytest -x /wazuh/tests/integration/test_aws/test_discard_regex.py
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.4.0
rootdir: /wazuh/tests/integration, configfile: pytest.ini
plugins: metadata-3.1.1, html-3.1.1
collected 17 items                                                                                                                                                                                        

wazuh/tests/integration/test_aws/test_discard_regex.py .................                                                                                                                            [100%]

===================================================================================== 17 passed in 365.98s (0:06:05) ======================================================================================
root@vagrant:/# pytest -x /wazuh/tests/integration/test_aws/test_basic.py 
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.4.0
rootdir: /wazuh/tests/integration, configfile: pytest.ini
plugins: metadata-3.1.1, html-3.1.1
collected 16 items                                                                                                                                                                                        

wazuh/tests/integration/test_aws/test_basic.py ................                                                                                                                                     [100%]

===================================================================================== 16 passed in 290.59s (0:04:50) ======================================================================================
root@vagrant:/# pytest -x /wazuh/tests/integration/test_aws/test_custom_bucket.py 
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.4.0
rootdir: /wazuh/tests/integration, configfile: pytest.ini
plugins: metadata-3.1.1, html-3.1.1
collected 2 items                                                                                                                                                                                         

wazuh/tests/integration/test_aws/test_custom_bucket.py ..                                                                                                                                           [100%]

====================================================================================== 2 passed in 79.20s (0:01:19) =======================================================================================
```

</details>

2024-05-07 12:43 UTC, GGP1 requested changes

2024-05-07 12:43 UTC, GGP1 commented on src/wazuh_testing/modules/aws/data_generator.py
> +def get_data_generator(bucket_type, bucket_name, creation_date, region) -> DataGenerator:
Now that the region is an input, could we validate that it is valid and fail early? Something like

```py
from boto3.session import Session
...

session = Session()
service_regions = session.get_available_regions('<service>')
if region not in service_regions:
    raise Exception(f"Invalid region, available regions are: {', '.join(service_regions)}")
```

2024-05-07 12:43 UTC, GGP1 commented on src/wazuh_testing/modules/aws/utils.py
> +        client (boto3.resources.base.ServiceResource): S3 client used to delete tbe file from the bucket.
```suggestion
        client (boto3.resources.base.ServiceResource): S3 client used to delete the file from the bucket.
```

2024-05-07 12:43 UTC, GGP1 commented on src/wazuh_testing/modules/aws/utils.py
> +        vpc = client.create_vpc(CidrBlock= '10.0.0.0/16',
```suggestion
        vpc = client.create_vpc(CidrBlock='10.0.0.0/16',
```

2024-05-07 12:43 UTC, GGP1 commented on src/wazuh_testing/utils/db_queries/aws_db.py
> +
```suggestion

```

2024-05-07 12:43 UTC, GGP1 commented on src/wazuh_testing/utils/database.py
> +def get_sqlite_fetch_one_query_result(db_path: str, query: str) -> tuple:
[db.execute_fetch_one_query](https://github.com/wazuh/qa-integration-framework/blob/1321b3bd96078745949ea2b55c3b5989f5e32387/src/wazuh_testing/tools/db_administrator.py#L41) is returning a list

```suggestion
def get_sqlite_fetch_one_query_result(db_path: str, query: str) -> list:
```

2024-05-07 12:43 UTC, GGP1 commented on src/wazuh_testing/utils/database.py
> +        result (tuple): Query result row.
```suggestion
        result (list): Query result row.
```

2024-05-07 13:40 UTC, fdalmaup commented on src/wazuh_testing/utils/database.py
> +def get_sqlite_fetch_one_query_result(db_path: str, query: str) -> tuple:
You are right, but the [documentation](https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.fetchone) mentions that a `tuple` is returned

2024-05-07 16:28 UTC, fdalmaup commented on src/wazuh_testing/modules/aws/data_generator.py
> +def get_data_generator(bucket_type, bucket_name, creation_date, region) -> DataGenerator:
Done

2024-05-08 12:37 UTC, GGP1 approved these changes
LGTM

2024-05-09 09:20 UTC, Selutario approved these changes
It's looking great.

2024-05-09 09:20 UTC, merged