Add `pywin32` and apply platform constants
wazuh/qa-integration-framework pull request #16
Opened 2023-07-05 20:10 UTC by QU3B1M

|Related Issue|
|---|
| https://github.com/wazuh/qa-integration-framework/issues/15|

## Description

This PR applies the platform constants on all the _platform conditionals_, it also adds a default timeout when the tests are being executed on Windows and gives 10 more seconds to the `FileMonitor` default monitor.

2023-07-05 21:03 UTC, TomasTurina requested changes

2023-07-05 21:03 UTC, TomasTurina commented on src/wazuh_testing/tools/file_monitor.py
> +    def start(self, callback: Callable, timeout: int = 30, accumulations: int = 1, only_new_events: bool = False) -> None:
Why 30, isn't 10 enough?

2023-07-05 21:03 UTC, TomasTurina commented on src/wazuh_testing/utils/configuration.py
> +        configuration = set_correct_prefix(configuration, PREFIX) # TODO: FIX THIS.
What is this comment?

2023-07-05 21:15 UTC, QU3B1M commented on src/wazuh_testing/tools/file_monitor.py
> +    def start(self, callback: Callable, timeout: int = 30, accumulations: int = 1, only_new_events: bool = False) -> None:
In the case of windows running on Actions nope, local it works correctly with 10s, but on the workflow it fails

2023-07-06 14:41 UTC, TomasTurina commented on src/wazuh_testing/utils/configuration.py
> +from wazuh_testing.constants.platforms import MACOS
Not necessary anymore.

2023-07-06 17:53 UTC, TomasTurina approved these changes

2023-07-06 17:53 UTC, merged