Migrate `FIM` dependencies
wazuh/qa-integration-framework pull request #21
Opened 2023-07-12 13:22 UTC by QU3B1M

| Related issue |
|----------------|
| #20                |

## Description

This PR applies all the required functions and classes required for the `FIM` Integration tests.

closes #20

2024-01-31 14:24 UTC, TomasTurina commented on src/wazuh_testing/modules/agentd/configuration.py
> +AGENTD_DEBUG = 'agent.debug'
Duplicated.

2024-01-31 14:26 UTC, TomasTurina commented on src/wazuh_testing/modules/fim/__init__.py
Add the log prefix here at least and use it in patterns.

2024-01-31 14:28 UTC, TomasTurina commented on src/wazuh_testing/modules/fim/configuration.py
Check if we can merge this with the content of /constants/keys/events.py to avoid duplication of code.

2024-01-31 14:28 UTC, TomasTurina commented on src/wazuh_testing/modules/fim/configuration.py
> +# Attributes constants.
Check if we can merge this with the content of `/constants/keys/events.py` to avoid duplication of code.

2024-01-31 14:29 UTC, TomasTurina commented on src/wazuh_testing/modules/fim/utils.py
> +import json
Missing header.

2024-01-31 14:30 UTC, TomasTurina commented on src/wazuh_testing/utils/commands.py
> +import subprocess
Missing header comment.

2024-02-23 19:58 UTC, TomasTurina commented on src/wazuh_testing/tools/monitors/base_monitor.py
Rebase. These changes are already in 4.9.0.

2024-03-15 16:11 UTC, TomasTurina requested changes

2024-03-15 16:11 UTC, TomasTurina commented on src/wazuh_testing/modules/syscheck/__init__.py
Remove folder syscheck.

2024-03-15 16:11 UTC, TomasTurina commented on src/wazuh_testing/utils/file.py
> +        return yaml.load(f,  yaml.Loader)
Check this change.

2024-03-15 16:55 UTC, sdvendramini commented on src/wazuh_testing/modules/agentd/configuration.py
> +AGENTD_DEBUG = 'agent.debug'
Done!

2024-03-15 16:58 UTC, sdvendramini commented on src/wazuh_testing/modules/fim/utils.py
> +import json
Done!

2024-03-15 17:02 UTC, sdvendramini commented on src/wazuh_testing/utils/file.py
> +        return yaml.load(f,  yaml.Loader)
`return yaml.load(f, yaml.Loader)` is newer!

2024-03-15 17:28 UTC, sdvendramini commented on src/wazuh_testing/modules/syscheck/__init__.py
Done!

2024-03-27 20:00 UTC, TomasTurina commented on src/wazuh_testing/modules/fim/__init__.py
Fill with PREFIX, it could be useful in the future.

2024-03-27 20:07 UTC, TomasTurina requested changes

2024-03-27 23:56 UTC, TomasTurina approved these changes

2024-03-28 17:49 UTC, merged