17788 migrate aws integration tests
wazuh/qa-integration-framework pull request #25
Opened 2023-07-24 12:08 UTC by EduLeon12

|Related issue|
|---|
| https://github.com/wazuh/wazuh/issues/17788 |

## Description

As part of https://github.com/wazuh/wazuh/issues/17788, AWS QA integration tests are being migrated to wazuh core repository. 
This PR tends to update the framework to be able to run AWS QA Tests. 

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2023-08-22 15:44 UTC, nico-stefani submitted a review, later dismissed
LGTM!

2023-08-25 11:31 UTC, Selutario commented on src/wazuh_testing/modules/aws/__init__.py
> +AWS_SERVICES_DB_PATH = Path(AWS_MODULE_PATH, 'aws_services.db')
Paths should probably be included in `wazuh_testing/constants/paths/aws.py`

2023-08-25 11:31 UTC, Selutario commented on src/wazuh_testing/modules/aws/__init__.py
> +ONLY_LOGS_AFTER_PARAM = '--only_logs_after'
Most of these constants might be placed under `wazuh_testing/constants/aws.py`

2023-08-25 11:31 UTC, Selutario commented on src/wazuh_testing/constants/paths/configurations.py
> +TEST_CASES_DIR = 'test_cases'
I'm not sure if `TEMPLATE_DIR` and `TEST_CASES_DIR` should be here since this file seems to contain only Wazuh paths. In any case, an extra blank line is required at the end.

2023-08-25 11:41 UTC, Selutario commented on src/wazuh_testing/modules/aws/event_monitor.py
> +    regex = re.compile(fr'.*DEBUG: Launching S3 Command: {" ".join(parameters)}\n*')
I think that all callback patterns should be defined in a file named `wazuh_testing/modules/aws/patterns.py` and then used inside `callbacks.generate_callback` as shown in the readme:
- https://github.com/wazuh/qa-integration-framework#usage

2023-08-28 15:35 UTC, TomasTurina requested changes

2023-08-28 15:35 UTC, TomasTurina commented on src/wazuh_testing/modules/aws/__init__.py
> +AWS_SERVICES_DB_PATH = Path(AWS_MODULE_PATH, 'aws_services.db')
I agree.

2023-08-28 15:35 UTC, TomasTurina commented on src/wazuh_testing/modules/aws/__init__.py
> +local_internal_options = {'wazuh_modules.debug': '2', 'monitord.rotate_log': '0'}
This is not ok nor necessary. Remove this. In the tests, you should use constants from monitord and modulesd. Example: https://github.com/wazuh/wazuh/blob/master/tests/integration/test_analysisd/test_all_syscheckd_configurations/test_check_rare_socket_responses.py#L72

2023-08-28 15:35 UTC, TomasTurina commented on src/wazuh_testing/modules/aws/event_monitor.py
> +    regex = re.compile(fr'.*DEBUG: Launching S3 Command: {" ".join(parameters)}\n*')
Yes, that's the way. Please, remove this file and move the patterns to `wazuh_testing/modules/aws/patterns.py`. For example: https://github.com/wazuh/qa-integration-framework/blob/main/src/wazuh_testing/modules/analysisd/patterns.py#L7
https://github.com/wazuh/wazuh/blob/master/tests/integration/test_analysisd/test_all_syscheckd_configurations/test_check_rare_socket_responses.py#L130

2023-08-28 15:35 UTC, TomasTurina commented on src/wazuh_testing/modules/aws/event_monitor.py
> +    regex = re.compile(fr'.*DEBUG: Launching S3 Command: {" ".join(parameters)}\n*')
If you want to create these functions because these callbacks are used in many places, please do this in the tests folder, not in the framework.
https://github.com/wazuh/qa-integration-framework/pull/14#discussion_r1290218901

2023-08-28 15:35 UTC, TomasTurina commented on src/wazuh_testing/modules/aws/db_utils.py
This file shouldn't exist. We should use functions from `utils/database.py` and `utils/db_queries/`, which use `DatabaseAdministrator`. Check https://github.com/wazuh/qa-integration-framework/pull/14#discussion_r1290234906.
This PR does this the right way with the `cve.db`: https://github.com/wazuh/qa-integration-framework/pull/14/files

2023-08-28 15:35 UTC, TomasTurina commented on src/wazuh_testing/modules/aws/exceptions.py
Why do we need this? Please remove or place this in the file where is used.

2023-08-28 15:35 UTC, TomasTurina commented on src/wazuh_testing/modules/aws/cli_utils.py
Can't we use/create more generic functions in `src/wazuh_testing/utils/`? These functions can be parametrized to be used in multiple places.

2023-08-28 15:35 UTC, TomasTurina commented on src/wazuh_testing/modules/aws/s3_utils.py
Rename to `utils.py`.

2023-08-28 15:35 UTC, TomasTurina commented on src/wazuh_testing/modules/aws/cloudwatch_utils.py
Move these functions all together to `utils.py`.

2023-09-26 12:06 UTC, EduLeon12 commented
Hi @TomasTurina all changes requested have been made.
I decided to reuse some of the db utils as you pointed out [here](https://github.com/wazuh/qa-integration-framework/pull/25#discussion_r1307561179) even tho they are not been pushed to the main branch yet, this will avoid merging issues in the future and allow reusability of the code.

Please, let me know what else should be changed so I can move forward to the core repository refactor.

2023-10-25 17:35 UTC, TomasTurina requested changes

2023-10-25 17:35 UTC, TomasTurina commented on src/wazuh_testing/constants/aws.py
I think these defines should be in `modules/aws` folder, some of them in `patterns.py` and some of them in the `__init__.p`y file. Besides, there are many others that are generic (example: `EVENT_TIME_FORMAT`, `PATH_DATE_FORMAT`, `SELECT_QUERY_TEMPLATE`, etc.), these should be in a more generic place.

2023-10-25 17:35 UTC, TomasTurina commented on src/wazuh_testing/constants/paths/aws.py
> +AWS_BINARY_PATH = Path(AWS_MODULE_PATH, 'aws-s3')
Add new line at the end of the file.

2023-10-25 17:35 UTC, TomasTurina commented on src/wazuh_testing/modules/aws/data_structures.py
I think you can place all of this in the `__init__.py` file.

2023-10-25 17:35 UTC, TomasTurina commented on src/wazuh_testing/modules/aws/data_structures.py
Or maybe directly in the` aws_db.py` file where they are used.

2023-11-08 19:27 UTC, EduLeon12 commented on src/wazuh_testing/constants/paths/aws.py
> +AWS_BINARY_PATH = Path(AWS_MODULE_PATH, 'aws-s3')
Done

2023-11-08 19:27 UTC, EduLeon12 commented on src/wazuh_testing/modules/aws/data_structures.py
Done

2023-11-29 14:50 UTC, TomasTurina submitted a review, later dismissed

2024-02-22 18:27 UTC, TomasTurina commented
Please, change base branch to 4.9.0.

2024-05-22 10:21 UTC, Selutario approved these changes

2024-05-23 17:48 UTC, TomasTurina reviewed
Change base to branch 4.9.0.

2024-05-29 15:42 UTC, Selutario approved these changes
LGTM

2024-05-29 15:46 UTC, Selutario approved these changes

2024-05-29 15:47 UTC, merged