Add script for pytest coverage test
wazuh/qa-integration-framework pull request #254
Opened 2024-10-22 14:33 UTC by RamosFe

|Related issue|
|---|
| https://github.com/wazuh/wazuh/issues/26466 |

## Description

Adds a script and the dependencies to get the Python unit tests coverage.

2024-10-22 19:23 UTC, GGP1 approved these changes
LGTM

2024-10-23 15:22 UTC, fdalmaup requested changes

2024-10-23 15:22 UTC, fdalmaup commented on requirements.txt
We need to check that the `jsonschema` and `pytest` upgrades do not break other tests that may use them. Please, run in https://github.com/wazuh/wazuh/pull/26470 any related test for verification.

2024-11-06 19:22 UTC, RamosFe commented on requirements.txt
Sent to run the test that uses the library. When the tests are finished, I will add the results to the mentioned PR.

2024-11-07 10:46 UTC, RamosFe commented
## Update - Tests

I ran all the tests that use the `qa-integration-framework` as well as the `jsonschemma` and `pytest` dependencies:

> All tests ran without any errors. The UT tests were run in the following PR https://github.com/wazuh/wazuh/pull/26470.

- **Syscollector Windows**: https://github.com/wazuh/wazuh/actions/runs/11710112533/job/32615899592
- **Syscollector Linux**: https://github.com/wazuh/wazuh/actions/runs/11710115470
- **Remoted**: https://github.com/wazuh/wazuh/actions/runs/11710151009/job/32615787491
- **Office365**: https://github.com/wazuh/wazuh/actions/runs/11710164964/job/32615832141
- **IT API Tier 0-1**: https://github.com/wazuh/wazuh/actions/runs/11710197723
- **IT API Tier 2**: https://github.com/wazuh/wazuh/actions/runs/11710213368
- **Authd**: https://github.com/wazuh/wazuh/actions/runs/11710289059/job/32616244603
- **AWS**: https://github.com/wazuh/wazuh/actions/runs/11710294963/job/32616263277
- **Agentd Linux**: https://github.com/wazuh/wazuh/actions/runs/11710356528
- **Agentd Windows**: https://github.com/wazuh/wazuh/actions/runs/11710362921/job/32616691717
- **Analysisd**: https://github.com/wazuh/wazuh/actions/runs/11710367391
- **Execd Linux**: https://github.com/wazuh/wazuh/actions/runs/11710375963/job/32616520020
- **Execd Windows**: https://github.com/wazuh/wazuh/actions/runs/11710377429
- **Enrollment Windows**: https://github.com/wazuh/wazuh/actions/runs/11710383151
- **Enrollment Linux**: https://github.com/wazuh/wazuh/actions/runs/11710305193
- **RBAC (Framework)**: https://github.com/wazuh/wazuh/actions/runs/11710390443
- **MsGraph**: https://github.com/wazuh/wazuh/actions/runs/11710392830
- **SCA Linux**: https://github.com/wazuh/wazuh/actions/runs/11710394375
- **SCA Windows**: https://github.com/wazuh/wazuh/actions/runs/11710395777
- **WazuhDB**: https://github.com/wazuh/wazuh/actions/runs/11710408274
- **Github Linux**: https://github.com/wazuh/wazuh/actions/runs/11710416059
- **Github Windows**: https://github.com/wazuh/wazuh/actions/runs/11710417211

2024-11-07 14:56 UTC, fdalmaup approved these changes
LGTM

2024-11-07 15:26 UTC, merged