Migrate framework dependencies for agentd ITs
wazuh/qa-integration-framework pull request #31
Opened 2023-08-11 11:17 UTC by mjcr99

|Related issue|
|---|
|Epic: https://github.com/wazuh/wazuh/issues/17427|
|Subtask: https://github.com/wazuh/wazuh/issues/17696

## Description
This PR includes all the necessary changes to give support to the migrated tests in the wazuh/wazuh repository. These tests will use this new structure. This PR removes all the unnecessary utilities, functions, classes, etc. that were not being used by the old ITs and adds some modifications.

2023-09-01 16:12 UTC, TomasTurina requested changes

2023-09-01 16:12 UTC, TomasTurina commented on src/wazuh_testing/modules/agentd/configuration.py
> +AGENTD_DEBUG= 'agent.debug'
Add new line at the end of the file.

2023-10-25 17:42 UTC, TomasTurina commented on src/wazuh_testing/modules/agentd/configuration.py
> +AGENTD_TIMEOUT = 'agent.recv_timeout'
Add new line at the end of the file.

2023-12-13 22:03 UTC, TomasTurina commented
Please, rebase your PR to add all latest changes.

2023-12-15 15:20 UTC, mjcr99 commented on src/wazuh_testing/modules/agentd/configuration.py
> +AGENTD_DEBUG= 'agent.debug'
Fixed with https://github.com/wazuh/qa-integration-framework/pull/31/commits/c2fe2409c925a501c02dee095e309f1b85631337

2023-12-15 15:20 UTC, mjcr99 commented on src/wazuh_testing/modules/agentd/configuration.py
> +AGENTD_TIMEOUT = 'agent.recv_timeout'
Fixed with https://github.com/wazuh/qa-integration-framework/pull/31/commits/c2fe2409c925a501c02dee095e309f1b85631337

2023-12-15 15:21 UTC, mjcr99 commented on src/wazuh_testing/tools/mitm.py
Fixed with https://github.com/wazuh/qa-integration-framework/pull/31/commits/c2fe2409c925a501c02dee095e309f1b85631337

2024-01-18 14:18 UTC, TomasTurina approved these changes

2024-01-19 18:09 UTC, TomasTurina approved these changes

2024-01-19 18:24 UTC, merged