Add retries to login and change default values
wazuh/qa-integration-framework pull request #39
Opened 2023-09-20 15:18 UTC by GGP1

|Related issue|
|---|
| Closes https://github.com/wazuh/wazuh/issues/18651 |

## Description

Changed the `login` function `login_attempts` parameter to make more than 1 attempt by default. Replaced the `sleep_time` parameter with `backoff_factor` to use a retry strategy for the requests in case of receiving connection refused errors.

## Tests

- https://github.com/wazuh/wazuh/actions/runs/6250608805
- https://github.com/wazuh/wazuh/actions/runs/6250616016
- https://github.com/wazuh/wazuh/actions/runs/6250621612

2023-09-25 12:39 UTC, fdalmaup approved these changes
LGTM!

2023-10-02 10:18 UTC, Selutario requested changes

2023-10-02 10:18 UTC, Selutario commented on src/wazuh_testing/modules/api/utils.py
> +    retry = Retry(total=None, connect=login_attempts, backoff_factor=backoff_factor)
`total` is the `Total number of retries to allow`, while `connect` is `How many connection-related errors to retry on` ([ref](https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry)). 

In my opinion it would be better to use `total`, is there any reason to use `connect` instead? We want it to be retried `login_attempts` times, regardless of the error type.

```suggestion
    retry = Retry(total=login_attempts, backoff_factor=backoff_factor)
```

2023-10-02 11:57 UTC, GGP1 commented on src/wazuh_testing/modules/api/utils.py
> +    retry = Retry(total=None, connect=login_attempts, backoff_factor=backoff_factor)
The reason is that it would block rate limit errors and the ones that are expected to occur. This may cause the rate limit to expire and thus the tests calls to pass. Strangely, this would happen even if I set it to `0` (I'm not sure if it's doing one retry there or not, but in the tests I ran it caused trouble) and setting it to `None` would use the default value.

Some tests are checking that the API is indeed rejecting more connections (test_DOS_blocking_system.py, test_bruteforce_blocking_system.py), so this way we just retry on connection-related issues

2023-10-03 09:42 UTC, Selutario approved these changes

2023-10-25 17:06 UTC, TomasTurina approved these changes

2023-10-25 17:06 UTC, merged