Framework migration of wazuh-db module
wazuh/qa-integration-framework pull request #43
Opened 2023-10-06 13:24 UTC by lsayanes

This PR includes all the necessary changes to give support to the `wazuh-db` migrated tests in the wazuh/wazuh repository. Those tests will use this new structure.

2024-01-15 19:55 UTC, TomasTurina requested changes
Rebase branch.

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/constants/executions.py
I think this file shouldn't be part of the framework.

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/tools/api.py
Remove this file. Use functions from `modules/api/utils.py`. Check comments from https://github.com/wazuh/qa-integration-framework/pull/48 that also apply here.

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/utils/agent_groups.py
> +import subprocess
Missing header.

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/utils/agent_groups.py
Rebase branch. This file already exists and is not necessary to create it again.

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/utils/configuration.py
> +def set_correct_prefix(configurations, new_prefix):
Remove empty function.

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/utils/configuration.py
> +def load_wazuh_configurations(yaml_file_path: str, test_name: str, params: list = None, metadata: list = None) -> object():
Remove this function. Use `load_configuration_template` instead or adapt it if necessary.

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/utils/database.py
> +def validate_interval_format(interval):
This function should be in `time.py` file. Remove `import numbers` once moved there.

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/utils/db_queries/global_db.py
> +def clean_agents_from_db():
Rebase branch. This function already exists.

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/utils/db_queries/global_db.py
> +def insert_agent_in_db(id=1, name='TestAgent', ip='any', registration_time=0, connection_status=0,
Remove. Use `create_or_update_agent`.

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/utils/db_queries/global_db.py
> +def insert_agent_into_group(total_agents):
Create a function to only set agent groups (for creating agents there is `create_or_update_agent`). Parametrize everything, this function should be generic.

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/utils/db_queries/global_db.py
> +def remove_db_agent(agent_id):
Remove. Use `delete_agent` instead (after rebase).

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/utils/file.py
> +
Missing empty space.

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/utils/file.py
> +def recursive_directory_creation(path):
Rebase and remove. This function already exists.

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/utils/manage_agents.py
> +def remove_all_agents(remove_type):
Remove. Use `clean_agents_from_db` instead (after rebase).

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/utils/db_queries/global_db.py
> +def list_agents_ids():
Remove. Not necessary if you use `clean_agents_from_db` (after rebase).

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/utils/services.py
> +from wazuh_testing.constants.paths import WAZUH_PATH
Why is this?

2024-01-15 19:55 UTC, TomasTurina commented on src/wazuh_testing/utils/time.py
> +class TimeMachine:
There is this open issue: https://github.com/wazuh/wazuh-qa/issues/4160

Can we avoid using this? Maybe another solution?

2024-01-31 13:46 UTC, TomasTurina commented on src/wazuh_testing/utils/configuration.py
> +import yaml
Remove import.

2024-01-31 13:46 UTC, TomasTurina commented on src/wazuh_testing/utils/configuration.py
> +from wazuh_testing.constants.paths import ROOT_PREFIX
Remove import.

2024-01-31 13:46 UTC, TomasTurina commented on src/wazuh_testing/utils/database.py
> -
Remove this change.

2024-01-31 13:49 UTC, TomasTurina commented on src/wazuh_testing/utils/time.py
> +
Missing empty space.

2024-02-05 10:12 UTC, mateocervilla commented on src/wazuh_testing/utils/database.py
> -
What do you mean? I removed an unused import `import numbers`

2024-02-15 21:02 UTC, TomasTurina approved these changes

2024-02-15 21:33 UTC, TomasTurina requested changes

2024-02-15 21:33 UTC, TomasTurina commented on src/wazuh_testing/utils/db_queries/agent_db.py
> +def agent_checksum_data(agent_id: str = '001', path: str = '/home/test/file'):
This function is not generic, please modify it.

2024-02-21 13:36 UTC, mauromalara commented
@mateocervilla @TomasTurina Please remove my name as a reviewer as I am no longer affiliated with Wazuh 🙏🏻 

Thanks!

2024-02-22 18:26 UTC, TomasTurina commented
Please, change base branch to 4.9.0.

2024-02-23 21:54 UTC, merged