Framework migration of SCA module
wazuh/qa-integration-framework pull request #44
Opened 2023-10-09 16:18 UTC by mateocervilla

Related to: https://github.com/wazuh/wazuh/issues/19087

## Description

This PR includes all the necessary changes to give support to the SCA migrated tests in the `wazuh/wazuh` repository. Those tests will use this new structure.

### Note:
In the `_match()` method from `BaseMonitor` class it was needed to append matches results to `callback_result` for cases when `accumulations` value is greater than 1

2023-10-12 14:05 UTC, tdrauncieal commented
tests done.
![2023-10-11_11-26](https://github.com/wazuh/qa-integration-framework/assets/93778492/d3da414e-6e29-4a14-acf4-e7b26d4d8100)

2023-10-12 14:05 UTC, tdrauncieal approved these changes

2023-10-25 18:08 UTC, TomasTurina commented on src/wazuh_testing/modules/sca/__init__.py
> +PREFIX = r'.*sca.*'
Add new line at the end of the file.

2023-10-25 18:16 UTC, TomasTurina requested changes

2023-10-25 18:16 UTC, TomasTurina commented on src/wazuh_testing/modules/sca/patterns.py
> +TEMP_FILE_PATH = '/tmp'
Add new line at the end of the file.

2023-10-25 18:16 UTC, TomasTurina commented on src/wazuh_testing/modules/sca/patterns.py
> +def callback_scan_id_result(line):
I would define these two functions in the tests, not in the framework.

2023-10-25 18:16 UTC, TomasTurina commented on src/wazuh_testing/tools/monitors/base_monitor.py
> +        if result:
Have you tested that this change doesn't break any test already migrated?

2023-10-25 18:16 UTC, TomasTurina commented on src/wazuh_testing/utils/file.py
> +    return file_list
Add new line at the end of the file.

2023-10-25 18:16 UTC, TomasTurina commented on src/wazuh_testing/modules/sca/patterns.py
> +TEMP_FILE_PATH = '/tmp'
Also, I think this define should be in `src/wazuh_testing/constants/paths/__init__.py`.

2023-10-25 18:16 UTC, TomasTurina commented on src/wazuh_testing/utils/file.py
> +    if sys.platform != 'win32':
Use `platforms.WINDOWS`.

2023-10-25 18:25 UTC, TomasTurina commented on src/wazuh_testing/modules/sca/patterns.py
> +def callback_scan_id_result(line):
Or instead, can't you use `generate_callback` function or refactor it to allow this in a more generic way?

2023-11-29 16:10 UTC, TomasTurina requested changes

2023-11-29 21:36 UTC, TomasTurina approved these changes

2023-11-29 21:42 UTC, TomasTurina approved these changes

2023-11-30 14:50 UTC, merged