Migrate framework dependencies of the API tests
wazuh/qa-integration-framework pull request #7
Opened 2023-06-12 16:18 UTC by mauromalara

| Related issues
|--
| closes #6 

## Description

This PR aims to migrate the dependencies of the API tests from the old framework (wazuh/wazuh-qa repo) to this brand-new repository, and also apply a refactor to remove unused code or duplicated code.

2023-07-04 19:13 UTC, TomasTurina requested changes
You need to rebase with `main`.

2023-07-04 19:13 UTC, TomasTurina commented on src/wazuh_testing/tools/simulators/remoted_simulator.py
You need to rebase your branch with `main` since this file was already added.

2023-07-04 19:13 UTC, TomasTurina commented on src/wazuh_testing/utils/configuration.py
> +        if test_case['metadata'] is None:
Why is this?

2023-07-04 19:13 UTC, TomasTurina commented on src/wazuh_testing/utils/file.py
> +def delete_file(path: Union[str, os.PathLike]) -> None:
There is already a function to do this, check `remove_file`.

2023-07-04 19:13 UTC, TomasTurina commented on src/wazuh_testing/utils/manage_agents.py
> +                subprocess.call([f"{WAZUH_PATH}/bin/manage_agents", "-r", f"{agent_id}"], stdout=open(os.devnull, "w"),
I think this path should be in `constants/paths/binaries`.

2023-07-04 19:13 UTC, TomasTurina commented on src/wazuh_testing/utils/manage_agents.py
> +                query_wdb(f"global delete-agent {str(agent_id)}")
Maybe a function in `db_queries` to keep everything more organized?

2023-07-12 11:34 UTC, mauromalara commented on src/wazuh_testing/constants/paths/analysisd.py
Done

2023-07-12 12:19 UTC, mauromalara commented on src/wazuh_testing/constants/syscollector.py
Done in 102201c

2023-07-12 12:19 UTC, mauromalara commented on src/wazuh_testing/constants/winevt.py
Done in 102201c

2023-07-12 12:25 UTC, mauromalara commented on src/wazuh_testing/modules/api/configuration.py
They're used in the API module only. In the future, if someone uses this in other suites they should consider moving this to a more abstract module; for now, it's ok.

2023-07-12 12:36 UTC, mauromalara commented on src/wazuh_testing/tools/queue_monitor.py
> +class Queue(queue.Queue):
Removed in rebase

2023-07-12 12:37 UTC, mauromalara commented on src/wazuh_testing/tools/simulators/remoted_simulator.py
Done in rebase

2023-07-12 12:40 UTC, mauromalara commented on src/wazuh_testing/utils/configuration.py
> +        if test_case['metadata'] is None:
This is because several tests do not need metadata... so we had 2 options:

1. Add dummy metadata in the YAML file with the test cases (ugliest)
2. Copy the test's configuration parameters into the test's metadata (chosen)

Otherwise, this util will fail because of the length of the metadata.

2023-07-12 12:46 UTC, mauromalara commented on src/wazuh_testing/modules/api/helpers.py
Done in 609a5d0

2023-07-12 12:47 UTC, mauromalara commented on src/wazuh_testing/utils/file.py
> +def delete_file(path: Union[str, os.PathLike]) -> None:
Done in ff1dc8d

2023-07-12 12:56 UTC, mauromalara commented on src/wazuh_testing/utils/manage_agents.py
> +                subprocess.call([f"{WAZUH_PATH}/bin/manage_agents", "-r", f"{agent_id}"], stdout=open(os.devnull, "w"),
Done in d8802d4

2023-07-12 12:56 UTC, mauromalara commented on src/wazuh_testing/utils/manage_agents.py
> +                query_wdb(f"global delete-agent {str(agent_id)}")
Done in d8802d4

2023-07-12 15:27 UTC, TomasTurina commented on src/wazuh_testing/constants/paths/ruleset.py
> +from wazuh_testing.constants.paths import WAZUH_PATH
```suggestion
from . import WAZUH_PATH
```

2023-07-12 16:46 UTC, TomasTurina requested changes

2023-07-12 16:46 UTC, TomasTurina commented on src/wazuh_testing/modules/api/helpers.py
Remove this file.

2023-07-12 16:46 UTC, TomasTurina commented on src/wazuh_testing/modules/api/utils.py
> +disable_warnings(exceptions.InsecureRequestWarning)
I don't like this. Can we solve this problem in a different way?

2023-07-12 16:46 UTC, TomasTurina commented on src/wazuh_testing/modules/api/utils.py
> +                'Content-Type': 'application/json',
```suggestion
                BASE_HEADERS,
```

2023-07-12 16:46 UTC, TomasTurina commented on src/wazuh_testing/constants/templates/syscollector.py
I'm rethinking this and it looks like these constants will only be used by the agent simulator as they are very specific. Don't you think we should move them inside the `tools/simulators/agent_simulator.py` file?

2023-07-12 16:46 UTC, TomasTurina commented on src/wazuh_testing/constants/templates/winevt.py
I'm rethinking this and it looks like these constants will only be used by the agent simulator as they are very specific. Don't you think we should move them inside the `tools/simulators/agent_simulator.py` file?

2023-07-12 18:47 UTC, mauromalara commented on src/wazuh_testing/modules/api/utils.py
> +                'Content-Type': 'application/json',
Done in 9753874

2023-07-12 18:47 UTC, mauromalara commented on src/wazuh_testing/modules/api/helpers.py
Done in 9753874

2023-07-12 18:47 UTC, mauromalara commented on src/wazuh_testing/constants/templates/syscollector.py
I agree. Done in 9753874

2023-07-12 18:47 UTC, mauromalara commented on src/wazuh_testing/constants/templates/winevt.py
I agree. Done in 9753874

2023-07-12 18:47 UTC, mauromalara commented on src/wazuh_testing/utils/database.py
> +import os
Done in 9753874

2023-07-12 19:56 UTC, QU3B1M commented on src/wazuh_testing/utils/configuration.py
> +        if test_case['metadata'] is None:
```suggestion
        if test_case.get('metadata') is None:
```

`test_case['metadata']` will raise an error if the key `metadata` is not present on the dict, I think it would be better to use the `.get()` function instead (it returns None if the key does not exist).

2023-07-12 19:56 UTC, QU3B1M commented on src/wazuh_testing/tools/simulators/agent_simulator.py
> +        compressed_event = zlib.compress(event)
Couldn't this be done using the `encode()` function of the `secure_message` util? something like whats on `RemotedSimulator` [line 210](https://github.com/wazuh/qa-integration-framework/blob/685415a1bd9978b48d75dca06c63a69b61f7e4ac/src/wazuh_testing/tools/simulators/remoted_simulator.py#L210)

2023-07-12 19:56 UTC, QU3B1M commented on src/wazuh_testing/tools/simulators/agent_simulator.py
> +            msg_decrypted = secure_message.decrypt(msg_remove_header, self.encryption_key, self.cypher)
I think the decryption could also be handled by the `secure_message` util. [Example](https://github.com/wazuh/qa-integration-framework/blob/685415a1bd9978b48d75dca06c63a69b61f7e4ac/src/wazuh_testing/tools/simulators/remoted_simulator.py#L195)

2023-07-12 20:39 UTC, mauromalara commented on src/wazuh_testing/utils/configuration.py
> +        if test_case['metadata'] is None:
Yes, would be better. Applied

2023-07-12 23:20 UTC, mauromalara commented on src/wazuh_testing/tools/simulators/agent_simulator.py
> +            msg_decrypted = secure_message.decrypt(msg_remove_header, self.encryption_key, self.cypher)
Done in 09357f2

2023-07-12 23:20 UTC, mauromalara commented on src/wazuh_testing/tools/simulators/agent_simulator.py
> +        compressed_event = zlib.compress(event)
Done in 09357f2

2023-07-12 23:21 UTC, mauromalara commented on src/wazuh_testing/constants/templates/winevt.py
Change not committed previously. Now done in 09357f2

2023-07-12 23:21 UTC, mauromalara commented on src/wazuh_testing/constants/templates/syscollector.py
Change not committed previously. Now done in 09357f2

2023-07-14 01:57 UTC, mauromalara commented on src/wazuh_testing/tools/simulators/agent_simulator.py
> +    def headers(self, agent_id, encrypted_event):
Done in [6463287](https://github.com/wazuh/qa-integration-framework/pull/7/commits/6463287d91a3df2069f5f0ea3efabfb960c3b407)

2023-07-14 14:47 UTC, TomasTurina approved these changes

2023-07-14 15:55 UTC, QU3B1M approved these changes

2023-07-14 19:34 UTC, merged