17426 migrate active response
wazuh/qa-integration-framework pull request #8
Opened 2023-06-13 20:11 UTC by QU3B1M

## Description

This PR implements the **`AuthSimulator`** and the **`RemotedSimulator`** required for the _Active Response_ test scenarios. It also comes with a **`SimulatorInterface`** that defines the base functionalities of a Simulator and some new functions on the util **`file.py`**

2023-06-29 18:18 UTC, QU3B1M commented on src/wazuh_testing/utils/certificate.py
> +class Certificate:
In this case is more comfortable to make it a class because of the values that are generated every time a new instance is created.

2023-06-29 18:53 UTC, QU3B1M commented on src/wazuh_testing/utils/secure_message.py
> +class SecureMessage:
In this case we could make it just a file with functions, I made it a class because the internal functions, changing it.

2023-06-29 20:05 UTC, QU3B1M commented on src/wazuh_testing/modules/execd/__init__.py
> +if platform.system() == 'Windows':
Applied on commit d1b2c0022736042bc30fdaae295be0656ea786eb

2023-06-29 20:06 UTC, QU3B1M commented on src/wazuh_testing/modules/execd/utils.py
Removed!

2023-06-29 20:06 UTC, QU3B1M commented on src/wazuh_testing/utils/file.py
> +def delete_file(path: str) -> None:
Removed on commit d1b2c0022736042bc30fdaae295be0656ea786eb

2023-06-29 20:35 UTC, TomasTurina requested changes
Don't remove `__init__.py` file from simulators folder. Keep it empty.

2023-06-29 20:35 UTC, TomasTurina commented on src/wazuh_testing/constants/paths/logs.py
> +    BASE_LOGS_PATH = WAZUH_PATH
Remove or rename, you are overwriting https://github.com/wazuh/qa-integration-framework/pull/8/files#diff-65a2317b04edb074347b8d6254f2103da060b61d90872d09eb71e3d55aab163eR10.

2023-06-29 20:35 UTC, TomasTurina commented on src/wazuh_testing/constants/paths/logs.py
> +    BASE_LOGS_PATH = os.path.join(WAZUH_PATH, 'logs')
Not necessary.

2023-06-29 20:35 UTC, TomasTurina commented on src/wazuh_testing/utils/certificate.py
> +class Certificate:
Should we move it to tools instead?

2023-06-30 11:43 UTC, QU3B1M commented on src/wazuh_testing/utils/certificate.py
> +class Certificate:
Not sure, anyway this is a util that wont be used by any test, only some tools uses it i think

2023-06-30 11:45 UTC, QU3B1M commented
> Don't remove `__init__.py` file from simulators folder. Keep it empty.

Its not deleted its just empty
![image](https://github.com/wazuh/qa-integration-framework/assets/44633633/170fdaa7-4ead-4875-9e51-e7b373438cea)

2023-07-03 13:44 UTC, TomasTurina commented on src/wazuh_testing/constants/paths/configurations.py
> +    SHARED_CONFIGURATIONS_PATH = os.path.join(BASE_CONF_PATH, 'shared')
Maybe we can move these 3 lines outside the if and else to avoid repeating them.

2023-07-03 13:50 UTC, TomasTurina commented on src/wazuh_testing/modules/active_response/__init__.py
> +# Copyright (C) 2015-2021, Wazuh Inc.
Remove comment if file is empty.

2023-07-03 13:51 UTC, TomasTurina commented on src/wazuh_testing/modules/execd/__init__.py
> +PREFIX = r'.*wazuh-execd.*'
Add empty line before.

2023-07-03 15:46 UTC, TomasTurina requested changes

2023-07-03 19:06 UTC, merged